// Builds data/wordCheck.js: packed, sorted 5-letter dictionaries plus a tiny
// binary-search checker, shared by the web apps' "is this a valid guess?" widget.
// Both the full app (index.html -> standalone) and the lite app inline this file,
// so the browser never needs the full 14,855-word array.
//
//   WORD_CHECK.find( word ) ->
//     0  not a valid guess
//     1  valid guess (not among the possible answers)
//     2  valid guess and a possible answer
//
// Re-run `node server/buildWordCheck.js` whenever the dictionaries change.
import fs from 'fs';
import guessWords from './guessWords.js';
import targetWords from './targetWords.js';

const pack = words => [ ...words ].sort().join( '' ); // every word is exactly 5 letters

const checkJs =
  `// GENERATED by server/buildWordCheck.js - do not edit by hand. Re-run that script
// after changing server/guessWords.js or data/targetWords.js.
// Packed 5-letter dictionaries: ${guessWords.length} guesses, ${targetWords.length} possible answers.
export default {
  gCount: ${guessWords.length},
  tCount: ${targetWords.length},
  g: "${pack( guessWords )}",
  t: "${pack( targetWords )}",
  find: function( w ) {
    var s = String( w ).toLowerCase();
    function has( packed ) {
      var lo = 0, hi = packed.length / 5 - 1;
      while ( lo <= hi ) {
        var mid = ( lo + hi ) >> 1;
        var cand = packed.substr( mid * 5, 5 );
        if ( cand === s ) return true;
        if ( cand < s ) lo = mid + 1; else hi = mid - 1;
      }
      return false;
    }
    if ( !has( this.g ) ) return 0;
    return has( this.t ) ? 2 : 1;
  }
};
`;

fs.writeFileSync( 'data/wordCheck.js', checkJs );
console.log( `Created data/wordCheck.js (${( checkJs.length / 1024 ).toFixed( 0 )} KB): ${guessWords.length} guesses, ${targetWords.length} answers` );
